### ISSUE TITLE
Allow to define partial paths

### ISSUE THREAD

**Issue by piranna** [prebuild/prebuild#112]
Allow to set just a fragment of the URL path as parameter for the `--download` argument to interpret it must to download the prebuild binary from the releases of same repo of the module. I know this is the default behaviour of the `--download` argument, what I'm asking for is to allow to set a custom format on the naming of the releases without needing to define the full URL.

**Comment by ralphtheninja** [comment]
`--download` is no longer in the scope of `prebuild`. Please re-open on `prebuild-install` instead if you still feel it's important to address.
