### ISSUE TITLE
Prebuild ABI

### ISSUE THREAD

**Issue by mathiask88** [prebuild/prebuild#123]
What if an addon author compiles his prebuilds e.g. on windows with VS2015? Node releases are currently build with VS2013. These two are not ABI compatible AFAIK.

**Comment by ralphtheninja** [comment]
Then maybe that addon author shouldn't compile using VS2015

**Comment by vweevers** [comment]
Incompatibilities like that are rare. When they do happen (for example https://github.com/sass/node-sass/issues/1283), the solution is indeed to compile the addon with an older VS.

Plus, nowadays AppVeyor defaults to VS2015, Travis For Windows uses VS2017, Node uses VS2017, and VS2015 and VS2017 are binary compatible.
