### ISSUE TITLE
Should respect npm's `cache` setting

### ISSUE THREAD

**Issue by jasonkarns** [prebuild/prebuild#130]
`prebuild` is deriving the npm cache directory [manually](https://github.com/mafintosh/prebuild/blob/b020f36eab0f14dd40f4aff4ad9ae71f7b7148b5/util.js#L57) instead of getting the path from npm's config; either via the npm-cli: `npm config get cache`/`npm get cache`, or from the environment variable made available by npm: `$npm_config_cache`.

This leads to `prebuild` using the wrong path when `cache` is set by the user to something other than the default.

**Comment by mathiask88** [comment]
@vweevers I think this can be closed. Download functionality was moved to `prebuild-install` and there we respect the `npm_config_cache` env.
