### ISSUE TITLE
Remove node-gyp dependency?

### ISSUE THREAD

**Issue by lgeiger** [prebuild/prebuild#143]
At the moment the package size of `prebuild` is quite large.
This is mainly caused by including `node-gyp` and `node-ninja` as a direct dependency.

Generally it is possible to rebuild native modules by executing `npm rebuild package-name` with the correct arguments. Such a approach would use the bundled `node-gyp` of npm which would significantly reduce the install time of `prebuild` and modules using it.

Am I missing a major downside of purely relying on `npm` to rebuild native modules?

**Comment by ralphtheninja** [comment]
I guess the main reason behind it was that we relied on a certain version of node-gyp (iirc for installing headers) which would make it difficult for users of older versions of node. That said, it probably isn't a big issue any longer.

**Comment by lgeiger** [comment]
Thanks for the explanation 👍 

Would you like to receive a PR for this or is it to dangerous to rely on the `node-gyp` version provided by `npm`?

**Comment by ralphtheninja** [comment]
It would be really nice if we could get rid of it reliably.

@mafintosh @juliangruber any thoughts on this?

**Comment by juliangruber** [comment]
It was [this commit](https://github.com/mafintosh/prebuild/commit/736fbeacde5bae1c237661771aff9156ed9953bb) from Juli 2015 that added node-gyp as a dependency, which was day one of this repository. I also can't find an issue talking about this, so this is probably good timing to revisit this decision. @mafintosh what do you think?

**Comment by lgeiger** [comment]
Great! I'll do some quick testing to see if my approach works.

**Comment by ralphtheninja** [comment]
@lgeiger Maybe we could still have it as a devDependency?

**Comment by lgeiger** [comment]
> Maybe we could still have it as a devDependency?

What would be the improvement in this case?

**Comment by ralphtheninja** [comment]
Ignore me :)
