### ISSUE TITLE
Add hyphen to `libc`?

### ISSUE THREAD

**Issue by piranna** [prebuild/prebuild#149]
On the docs it seems that the platform and the libc fields in the download URL are concatenated, shouldn't them to be separated by an hyphen?

Also, how to setup a `libc` agnostic build? Maybe with `*`?

**Comment by corbinu** [comment]
@piranna When I added libc the thought was to not break compatibility. So * is simply no libc in the url. As for the hyphen given that all platform & architecture combinations have a default LIBC the thought was to simply add it to the end of the platform. That way it worked for those who needed it but didn't confuse/complicate things for those who did not. However I would not be opposed to a change.

For usage feel free to take a look at this repo of mine: https://github.com/corbinu/couchnode/releases

**Comment by piranna** [comment]
Good to know you already have builds using `musl` :-) I asked about the hyphen to use it as separator for each field, I understand about your point of all platforms has a default libc but not always it's glib, that'w what's being assumed here. In fact, there are other systems like Alpine or (my) NodeOS that are musl-based, so by not defining the libc would download by default a glibc-based prebuild and it will not work... :-/ I don't disagree being glibc as the default one, but there should be then some way to detect the platform is not glibc-based and do the correct request automatically...

**Comment by corbinu** [comment]
@piranna I am fine if you can find a way to reliably detect a Linux's default LIBC. I looked and had a very hard time finding one. In my case I simply have set LIBC=musl by default in all my Alpine containers. I don't know if prebuilt would consider adding the hyphen a breaking change. However I defiantly think that step one would be to find a way to detect the the LIBC for a particular Linux disto. If you can do that I would be happy to help you with a PR to integrate it into prebuild.

**Comment by piranna** [comment]
> I am fine if you can find a way to reliably detect a Linux's default LIBC

Maybe asking politely directly to it? :-)

```sh
piranna@slimbook-C16B:~/Trabajo/HBP/whole neuron/prueba11$ readlink /lib/ld-linux.so.2 
i386-linux-gnu/ld-2.24.so
```

This is from my Ubuntu machine, is a 64 bits machine but definitely is `glibc`-based, as it shows the `gnu` string in the symbolic link, for a `musl`-bases system it would have been `i386-linux-musl/ld-2.24.so`. Don't know what would be the string in other systems, but probably they would be checked in a similar way.


> I don't know if prebuilt would consider adding the hyphen a breaking change

It could be fixed by doing several requests if the url is not specified, one with the libc and if it fails and the libc is not specified one without it as currently.

**Comment by corbinu** [comment]
That file `/lib/ld-linux.so.2` doesn't run on my 14.04 Ubuntu server. As I said before I looked at quite a few ways and there did not seem to be any one way that works across all Linux distros that I know if

**Comment by piranna** [comment]
That's strange... That's the path where the default linker is located, if it's not using it then it should use a similar symlink in /lib.

**Comment by corbinu** [comment]
It doesn't exist in the main alpine docker container either.

**Comment by piranna** [comment]
Then how are dynamic libraries linked? Are they using directly their correct platform linker? If so, then th3 system has multiarch support and there should be several folders inside /lib, one for each arch and libc.

Another option would be to simply have glibc unconditionally by default and allow to set a different one using the --libc flag...

**Comment by corbinu** [comment]
I have no idea. It may be a similar file I just tried running your command and no luck.

That is the current behavior... like all prebuilt args it is a environment variable or a flag... I added that to the README when I merged the feature

**Comment by piranna** [comment]
> I have no idea. It may be a similar file I just tried running your command and no luck.

At http://unix.stackexchange.com/questions/120380/what-c-library-version-does-my-system-use there are several suggerences about how to get the c library version. Interesting the last one, doing `ldd /bin/sh`, maybe it would makes sense to do it with the Node.js executable itself since there could be versions for several libc on the same system (crazy, I know) and we would only be interested on the current one we are executing, isn't it? At http://www.linux-pages.com/2011/04/how-to-find-out-my-libc-glibc-version/ check `/lib/libc.so`, that would be another option.


> That is the current behavior... like all prebuilt args it is a environment variable or a flag... I added that to the README when I merged the feature

Yes... but the problem is that the current code threat `linux` and `linuxgnu` as different libc, while they are in fact the same. What I'm saying is that when a libc is not defined, use it internally as `gnu` instead of an empty string (or viceversa, for backwards compatibility, but uglier).

**Comment by corbinu** [comment]
If you want to create a new npm module that can reliably determine the default libc of all Linux distros (or better yes all OS supported by node). Then it should be easy to make that the default value for libc rather than "none" and falling back to the previous behavior.

Again this is not a change I would oppose. However the current behavior is not a "problem" at least for my use case.

**Comment by lovell** [comment]
Hello, I ran into this problem and created [detect-libc](https://github.com/lovell/detect-libc) to deal with it.

It provides a cross-platform command line process wrapper that sets the `LIBC` environment variable to the name of the system's libc only when run on non-glibc Linux. It currently supports detection of musl and can easily be expanded for other libc families.

Example `package.json` usage:
```
  "scripts": {
    "install": "detect-libc prebuild-install || node-gyp rebuild",
    "test": "mocha && detect-libc prebuild-ci"
  }
```

**Comment by piranna** [comment]
Could you be able to do a pull-request instegrating `detect-libc` inside `prebuild` modules, so detection is done automatically?

**Comment by corbinu** [comment]
@lovell Great!! If you want I can integrate it otherwise.

**Comment by lovell** [comment]
prebuild integrated with detect-libc over 5 years ago so hopefully we can close this issue now, thanks all.
