### ISSUE TITLE
Create an organization

### ISSUE THREAD

**Issue by piranna** [prebuild/prebuild#158]
Create an organization where to hold both prebuild and prebuild-install projects.

**Comment by juliangruber** [comment]
+-0 from me

**Comment by mathiask88** [comment]
No strong opinion from me but an organization could centralize all `prebuild` related projects. Adding some hints to every useful repository regarding the `prebuild` project in the README would do it also, because I found https://github.com/juliangruber/prebuild-ci today that is super useful, because I don't own a mac and OSX VMs are not that straightforward :)

**Comment by fanatid** [comment]
+1 for organization, current repositories I know about:

https://github.com/mafintosh/prebuild
https://github.com/mafintosh/prebuild-install
https://github.com/juliangruber/prebuild-ci
https://github.com/mafintosh/prebuildify
https://github.com/mafintosh/node-gyp-build

**Comment by mafintosh** [comment]
I'm okay moving stuff to an org if people want it as long as we keep things simple. Is that something I have to setup?

**Comment by piranna** [comment]
> Is that something I have to setup? (github noob)

That's only create an organization in the same link to create a new repo, and transfer the repos to the organization from their settings tab. Don't doubt to ask for help, I have done it several times :-)

**Comment by ralphtheninja** [comment]
> I'm okay moving stuff to an org if people want it as long as we keep things simple. Is that something I have to setup? (github noob)

You or someone else. There's functionality in github to transfer repositories which is handy if you want to keep issue/pr history etc (repo settings page)

**Comment by piranna** [comment]
I have just created the [organization](https://github.com/prebuild). @mafintosh, I have just send you an invitation to it as owner of the organization, just accept it and later you'll only need to go to each one of the projects an transfer the ownership of the projects to the organization, on the "settings" tab. @juliangruber, I have also send you an invitation so you can also transfer your `prebuild-ci` repo.

**Comment by fanatid** [comment]
1 of 5 repositories moved, not big progress here :)

**Comment by piranna** [comment]
> 1 of 5 repositories moved, not big progress here :)

We can continue discussion while that :-) What about a logo? ;-)

**Comment by mathiask88** [comment]
Would be cool to see some progress here :)

BTW I just set up `prebuild `, `prebuild-install ` and `prebuild-ci` in my project. It was super easy and first try :ok_hand:
