### ISSUE TITLE
Missing build log when running as npm script

### ISSUE THREAD

**Issue by apihlaja** [prebuild/prebuild#166]
I noticed build log is missing after first 2 lines ie. after the first build task kicks off (example [log](https://ci.appveyor.com/project/apihlaja/node-irsdk/build/111/job/x3f9toe50t7uadby#L516)).

By looking [prebuild.js](https://github.com/mafintosh/prebuild/blob/0983447d48bca18fc534e774af9b728ffa5b6a34/prebuild.js#L16) it's obvious there is supposed to be more logging (plenty of other `buildLog` calls). With verbose mode, that's the last thing in log:  https://github.com/mafintosh/prebuild/blob/0983447d48bca18fc534e774af9b728ffa5b6a34/gyp.js#L24

If I run prebuild directly (`./node_modules/.bin/prebuild`) instead of using npm script, I get much more logging (spawn args etc might belong to verbose mode).

Appveyor build had npm v4, but I have locally npm v3.10.10 and it does same. 

`leveldown` [build log looks similar](https://travis-ci.org/Level/leveldown/jobs/198592472#L877) so it doesn't look like issue is related to Windows weirdness.

**Comment by ralphtheninja** [comment]
Terve! Which log entries exactly are missing when running as npm script?

**Comment by apihlaja** [comment]
[prebuild.js](https://github.com/mafintosh/prebuild/blob/0983447d48bca18fc534e774af9b728ffa5b6a34/prebuild.js#L16) alone has 5 buildLog calls. As far as I know, all of them are on same log level so all of them should be visible.

In my example log, prebuild task begin on [line 513](https://ci.appveyor.com/project/apihlaja/node-irsdk/build/111/job/x3f9toe50t7uadby#L513). Search for `prebuild info`, there is only 2 log lines. And the task have `--all` flag so at least I'd expect to have that kind of log line for all versions:

`prebuild info build Preparing to prebuild node-irsdk@2.0.0 for node 0.10.48 on win32-x64 using node-gyp`

**Comment by ralphtheninja** [comment]
Ok. Now I see what you mean. This is indeed weird. I'm wondering if building the code (node-gyp) somehow changes the log level under our feet.

What happens if you try `npm run prebuild --verbose`?

**Comment by apihlaja** [comment]
Definitely something happens during gyp tasks. In verbose mode, logs still disappear after first gyp task, thats the last thing in log: https://github.com/mafintosh/prebuild/blob/0983447d48bca18fc534e774af9b728ffa5b6a34/gyp.js#L24
