### ISSUE TITLE
Merge in prebuildify and release as new major

### ISSUE THREAD

**Issue by mafintosh** [prebuild/prebuild#168]
As soon as @juliangruber finishes all his awesome CI build stuff we should just merge in [prebuildify](https://github.com/mafintosh/prebuildify) here and release as a new major

**Comment by ralphtheninja** [comment]
Consider renaming `--preinstall` and `--postinstall` to just `--pre` and `--post`

**Comment by fanatid** [comment]
@mafintosh sorry, can you give more details?
What CI build stuff @juliangruber develop? [prebuild-ci](https://github.com/prebuild/prebuild-ci)?
Do you want to move part of prebuildify to prebuild?

**Comment by juliangruber** [comment]
@fanatid we're working on a flow where you use [prebuild-ci](https://github.com/prebuild/prebuild-ci) to build your releases on CI and upload them to github, then use [travis-watch](https://github.com/juliangruber/travis-watch) (and the to-be-written appveyor-watch) to wait until all are done, then publish them inside the node module with the prebuildify approach

**Comment by fanatid** [comment]
@juliangruber thank you for explanation, looks similar to what I suggested in https://github.com/mafintosh/prebuildify/issues/6#issuecomment-286426552
prebuildify will be deprecated after new prebuild major version, I'm understand correctly?

**Comment by juliangruber** [comment]
ah, nice! yes, after its functionality has been merged into prebuild

**Comment by piranna** [comment]
What's the difference between `prebuild` and `prebuildify`?

**Comment by ralphtheninja** [comment]
@piranna https://github.com/mafintosh/prebuildify

**Comment by ralphtheninja** [comment]
@piranna Basically, bundle the prebuilds inside the npm package when publishing.

**Comment by piranna** [comment]
> @piranna Basically, bundle the prebuilds inside the npm package when publishing.

So they binaries will be inside the tarball served by npm registry? I find this bad... not only will give more presure to their servers and will download the binaries for ALL the platforms, but also would not offer tarballs for the binaries as it's currently done when publishing on GitHub. I would like to still have an option to publish the prebuilds on Github, both automatically or by generating them and uploading them myself.

**Comment by mathiask88** [comment]
@piranna The functionality of `prebuildify` will extend and not replace the current features of `prebuild` in my understanding. So the user can choose the way he wants to go. There are several pros and cons for both approaches.

**Comment by piranna** [comment]
> The functionality of prebuildify will extend and not replace the current features of prebuild in my understanding

I was worried about that, my understand was that it was going to replace the current behaviour.

**Comment by ralphtheninja** [comment]
> @piranna The functionality of prebuildify will extend and not replace the current features of prebuild in my understanding. So the user can choose the way he wants to go. There are several pros and cons for both approaches.

You said what I was about to say :)

So maybe then we shouldn't merge `prebuild` and `prebuildify` and just keep them as separate repositories.

**Comment by vweevers** [comment]
> So maybe then we shouldn't merge `prebuild` and `prebuildify` and just keep them as separate repositories.

👍
