### ISSUE TITLE
building native modules with node-gyp completely broken for 0.12?

### ISSUE THREAD

**Issue by ralphtheninja** [prebuild/prebuild#188]
When releasing `leveldown@1.9.0` I noticed the following error for node 0.12 https://travis-ci.org/Level/leveldown/jobs/280998747

Does this mean that `node-gyp` no longer can build for node 0.12?

**Comment by juliangruber** [comment]
Yes it seems so, unless we pin to an older version of node-gyp. We should also just drop .12

**Comment by vweevers** [comment]
Apparently 0.x was dropped a while ago: https://github.com/nodejs/node-gyp/pull/1212

**Comment by vweevers** [comment]
From a quick browse through [dependents of prebuild](https://github.com/nice-registry/native-modules/tree/master#all_dependents_of_prebuild), this potentially affects:

- https://github.com/couchbase/couchnode
- https://github.com/frida/frida-node
- https://github.com/level/leveldown-hyper
- https://github.com/octalmage/robotjs
- https://github.com/mafintosh/node-sodium-prebuilt
- https://github.com/datproject/rabin
- https://github.com/mathiask88/node-snap7
- https://github.com/wadey/node-microtime

**Comment by vweevers** [comment]
I might have missed some: those that have custom (hard-to-grep) build processes, no travis or appveyor, and/or no `engines.node` in `package.json`.
