### ISSUE TITLE
Should we release a new patch with reverted dependencies to make 0.12 work?

### ISSUE THREAD

**Issue by ralphtheninja** [prebuild/prebuild#191]
[![](https://api.gh-polls.com/poll/01C0KTMTJXZ1HPZNW12JTCJMP1/Yes.%20It's%20important%20that%20prebuild%20works%20on%20all%20platforms.)](https://api.gh-polls.com/poll/01C0KTMTJXZ1HPZNW12JTCJMP1/Yes.%20It's%20important%20that%20prebuild%20works%20on%20all%20platforms./vote)
[![](https://api.gh-polls.com/poll/01C0KTMTJXZ1HPZNW12JTCJMP1/No.%20Too%20much%20hassle%20to%20revert%20dependencies%20just%20to%20please%200.12%20users.)](https://api.gh-polls.com/poll/01C0KTMTJXZ1HPZNW12JTCJMP1/No.%20Too%20much%20hassle%20to%20revert%20dependencies%20just%20to%20please%200.12%20users./vote)

Also see https://github.com/prebuild/prebuild/issues/188 and https://github.com/prebuild/prebuild/pull/190

**Comment by ralphtheninja** [comment]
Note that this should only be related to actually _building_ on 0.12, not building _for_ 0.12 :)

**Comment by mathiask88** [comment]
Yes should be quite easy to pin these dependencies to the latest working 0.x version, but I also think that noone will ever need it. And if so it's still fixable.
