### ISSUE TITLE
Add support for N-API builds

### ISSUE THREAD

**Issue by jschlight** [prebuild/prebuild#220]
The [N-API Working Group](https://github.com/nodejs/abi-stable-node) is interested in adding support to prebuild for N-API builds. We have an [issue](https://github.com/nodejs/abi-stable-node/issues/291) open on our project site where we're discussing possible changes.

Like I did for [node-pre-gyp](https://github.com/mapbox/node-pre-gyp/pull/345), I'm ready to start work on a pull request for prebuild. But I'd appreciate any comments or suggestions from the prebuild maintainers and users before I start serious work.

**Comment by jschlight** [comment]
@ralphtheninja I've started work on the PR and will post it when it's ready.

**Comment by jschlight** [comment]
There are now two PRs. One for [`prebuild`](https://github.com/prebuild/prebuild/pull/228) and another for [`prebuild-install`](https://github.com/prebuild/prebuild-install/pull/87).

**Comment by vweevers** [comment]
Closing because both PRs have landed. Thanks @jschlight!
