### ISSUE TITLE
Problem with prebuild module

### ISSUE THREAD

**Issue by rahmonzoda** [prebuild/prebuild#231]
Hi guys, thanks for the excellent library, but i have an error that i can't fix.
I creaded prebuild module and publish that here [https://github.com/rahmonzoda/node-desktop-idle/releases](url)
The module is also installed normally, but I get this error when i try use that

os: osx 10.14
node: node v10.11.0
npm: 6.4.1

dyld: lazy symbol binding failed: Symbol not found: __ZN2v816FunctionTemplate3NewEPNS_7IsolateEPFvRKNS_20FunctionCallbackInfoINS_5ValueEEEENS_5LocalIS4_EENSA_INS_9SignatureEEEiNS_19ConstructorBehaviorENS_14SideEffectTypeE
  Referenced from: /Users/ubayd/Work/chronos/simple-samples/activity-monitor/node_modules/desktop-idle/build/Release/desktopIdle.node
  Expected in: flat namespace

dyld: Symbol not found: __ZN2v816FunctionTemplate3NewEPNS_7IsolateEPFvRKNS_20FunctionCallbackInfoINS_5ValueEEEENS_5LocalIS4_EENSA_INS_9SignatureEEEiNS_19ConstructorBehaviorENS_14SideEffectTypeE
  Referenced from: /Users/ubayd/Work/chronos/simple-samples/activity-monitor/node_modules/desktop-idle/build/Release/desktopIdle.node
  Expected in: flat namespace

**Comment by ralphtheninja** [comment]
My guess is you're linking with something that can't be found on the target system, i.e. where you are downloading it.

**Comment by lovell** [comment]
@rahmonzoda If you're using Electron then `electron-rebuild` is required - see https://github.com/electron/electron/issues/14167

**Comment by maxbrunsfeld** [comment]
I'm seeing something similar with the mac os binaries here: https://github.com/tree-sitter/node-tree-sitter/releases/tag/v0.13.19.

The binaries were compiled on a macOS worker on Travis-CI. But users who download them on macOS 10.14 Mojave are getting the same dynamic linking error when loading the module:

```
dyld: lazy symbol binding failed: Symbol not found: __ZN2v816FunctionTemplate3NewEPNS_7IsolateEPFvRKNS_20FunctionCallbackInfoINS_5ValueEEEENS_5LocalIS4_EENSA_INS_9SignatureEEEiNS_19ConstructorBehaviorENS_14SideEffectTypeE
  Referenced from: /the/project/node_modules/tree-sitter/build/Release/tree_sitter_runtime_binding.node
  Expected in: flat namespace
```

**Comment by maxbrunsfeld** [comment]
Disregard the above comment; it was actually an electron / node incompatibility.

**Comment by bendemboski** [comment]
I suspect the issue you are seeing is caused by [this](https://github.com/lgeiger/node-abi/issues/54) bug.

**Comment by vweevers** [comment]
@rahmonzoda As noted above, the problem might be an Electron incompatibility, which can be solved by using `electron-rebuild` and/or (if caused by the ABI bug) by updating `prebuild-install`.

If that is not the case (e.g. you're not using Electron), feel free to reopen with more information. Thanks!
