### ISSUE TITLE
Failing CI

### ISSUE THREAD

**Issue by DanielRuf** [prebuild/prebuild#237]
https://ci.appveyor.com/project/mathiask88/prebuild/builds/20023810

**Comment by vweevers** [comment]
May have been a temporary failure or fixed on AppVeyor's side in the mean time.

@mathiask88 can you restart that build?

**Comment by vweevers** [comment]
Nevermind. It was not a temporary failure. We should replace `Update-NodeJsInstallation` with `Install-Product node` according to [this thread](https://help.appveyor.com/discussions/problems/18115-nodejs-11-node-is-not-recognized-as-an-internal-or-external-command-operable-program-or-batch-file).
