### ISSUE TITLE
Create organizational AppVeyor account

### ISSUE THREAD

**Issue by vweevers** [prebuild/prebuild#241]
@mathiask88 I'd like to be able to cancel and restart builds on AppVeyor to speed up development. Can you add me to the account? Email me if needed (address in GH profile) (I could not find yours). Thanks! 

In case you use your account for other projects and thus cannot share access, we can create a new organizational account. That's also what I'll do if you don't have the time to attend to this. ❤️

**Comment by mathiask88** [comment]
Hey @vweevers, yes I use this AppVeyor account for another project but I set up a `prebuild` user role and added the whole `Prebuilder` team. So everyone should have access to the `prebuild` stuff in my account now. However we should go for a new account for this organization to be fully independent. But for now you should be g2g.

**Comment by vweevers** [comment]
Awesome! Thanks for the quick action! I'll repurpose this issue to be about opening a new account.

**Comment by vweevers** [comment]
Duplicate of https://github.com/prebuild/prebuild-install/issues/62
