### ISSUE TITLE
Error from GitHub: Not Found

### ISSUE THREAD

**Issue by Armaldio** [prebuild/prebuild#243]
Everytime I try to publish a release from Travis, this error pops: 
```
Error from GitHub: Not Found
```

Here's my package.json file specify the correct url: 

```json
{
  "name": "greenworks-prebuilds",
  "version": "0.15.0",
  "description": "Prebuild binaries for greenworks",
  "licenses": [
    {
      "type": "MIT",
      "url": "https://github.com/ElectronForConstruct/greenworks-prebuilds/blob/master/LICENSE"
    }
  ],
  "repository" : {
    "type" : "git",
    "url": "git@github.com:ElectronForConstruct/greenworks-prebuilds.git"
  }
}
```

Also the command I'm using: 
```bash
npx prebuild --all -u $GH_TOKEN --verbose
```

**Comment by vweevers** [comment]
- Can you share the full log (preferably in a gist)?
- That error comes from `ghutils`. The latest version should include more info if GitHub has it. What's the output of `npm ls ghutils`?
- Just a hunch, maybe you didn't push a tag?

**Comment by Armaldio** [comment]
Thanks for the quick answer.

- Can you see this log maybe ?
https://travis-ci.com/ElectronForConstruct/greenworks-prebuilds/jobs/182608155

- prebuild is not installed locally, so I doubt `npm ls ghutils` would return anything. I'm running prebuild through `npx` as mentionned in the previous message.

- What do you mean by `you didn't push a tag` ?

**Comment by vweevers** [comment]
> prebuild is not installed locally, so I doubt npm ls ghutils would return anything. I'm running prebuild through npx as mentionned in the previous message.

OK, suspected that. Wanted to confirm because if prebuild wás locally installed then `npx` would use that.

> What do you mean by you didn't push a tag

The typical flow is to create a git tag (usually with `npm version ..`) then push that to GitHub with `git push --follow-tags`, at which point `prebuild` can make a release from that tag.

**Comment by Armaldio** [comment]
Ah, I think that the tag thing.
I must have misinterpreted the docs. It says that if a release don't exist,
it will be created, but indeed, if the auto release it based on a tag, it
will not work in my case.

I'm going to try to push a tag and will eventually close the issue if it
worked.

Thanks for the clarification.

Le mer. 6 mars 2019 à 11:07, Vincent Weevers <notifications@github.com> a
écrit :

**Comment by Armaldio** [comment]
I've puhed a tag v0.1 as seen here: https://github.com/ElectronForConstruct/greenworks-prebuilds/tags

Same error: Not found

**Comment by Armaldio** [comment]
Following on this, I found the root cause of the problem.
I was cloning a repo, cding to it a trying to push from there but it took the infos from the wrong package.json

I'm now doing: 
```
- cd greenworks
- ...
- npx prebuild --all --verbose
- mv prebuilds ../prebuilds
- cd ..
- npx prebuild --upload-all -u $GH_TOKEN
```

But the last command fail: `Bad Credentials`. I'm pretty sure the token is okay. Is it really possible to specify `-u` flag here ? If not, how do I do that ?

**Comment by vweevers** [comment]
> Is it really possible to specify -u flag here?

No. This part of the argument handling is a bit weird. You'll want:

`npx prebuild --upload-all $GH_TOKEN`

**Comment by Armaldio** [comment]
That's it!

Thank you for your support and keep up the great work :)

**Comment by Jimbly** [comment]
To help others who might come across this issue while troubleshooting: I also encountered this error, but the root of the problem was that I had forked a repo and forgot to update the `repository` field in package.json, so it was, presumably, trying to push to the wrong repo (but getting "not found" instead of some more useful error, I guess).
