### ISSUE TITLE
prebuild --all fail on MacOS

### ISSUE THREAD

**Issue by Armaldio** [prebuild/prebuild#244]
Oops, another issue.

Trying to do:

1. 

	- npx prebuild -t 1.4.10 -r electron
	- npx prebuild -t 0.26.6 -r node-webkit
	- npx prebuild -t 0.26.6 -r node

2. 

	- npx prebuild --all

When doing 1., it works fine, either linux and mac

When doing 2, exact same configuration, it fail on MacOS with error message: `clang: error: invalid deployment target for -stdlib=libc++ (requires OS X 10.7 or later)`

Build log for 1.: https://travis-ci.com/ElectronForConstruct/greenworks-prebuilds/jobs/182857039 ✅
Build log for 2.: https://travis-ci.com/ElectronForConstruct/greenworks-prebuilds/jobs/182853598 ❌

**Comment by vweevers** [comment]
> `- npx prebuild -t 0.26.6 -r node`

Are you sure that's what you meant to do? 0.26.6 is the same as the node-webkit target.

> clang: error: invalid deployment target for -stdlib=libc++ (requires OS X 10.7 or later)

No idea. But `export MACOSX_DEPLOYMENT_TARGET=10.7` may help according to [this](https://stackoverflow.com/a/23876600) and [this](https://github.com/Valloric/YouCompleteMe/issues/1683#issuecomment-140274090).

**Comment by Armaldio** [comment]
Here I was just tryin to debug, and what I discovered is that building specific version does work, while building everything using `--all` doesn not.

About thee environment variable, it's already there as seen in the configuration: https://travis-ci.com/ElectronForConstruct/greenworks-prebuilds/builds/103429232/config

Maybe an issue with a specific version ?

**Comment by vweevers** [comment]
> About thee environment variable, it's already there as seen in the configuration: https://travis-ci.com/ElectronForConstruct/greenworks-prebuilds/builds/103429232/config

👍 Maybe it isn't available to subprocesses? Just spitballing, I don't know how `eval` works.

> Maybe an issue with a specific version ?

That's likely, yes. Easy to confirm by building the same target manually.

**Comment by Armaldio** [comment]
I chose a path a little different with the help of a node script. In this way, it does not stop on first error and I have more control over what I generate.
https://github.com/ElectronForConstruct/greenworks-prebuilds/blob/develop/index.js
