### ISSUE TITLE
strip command output for multiple files incorrect in 8.2.0

### ISSUE THREAD

**Issue by dhritzkiv** [prebuild/prebuild#246]
As of v8.2.0, the `--strip` option no longer generates a valid strip(1) output:

```sh
strip build/Release/webgl.node,build/Release/obj.target/webgl.node --strip-all
```

which results in `No such file`.

---

Before (in v8.1.2), I believe the output was simply either one of:

```sh
# it may only be stripping the first file
strip build/Release/webgl.node --strip-all
```

or

```sh
# note the space
strip build/Release/webgl.node build/Release/obj.target/webgl.node --strip-all
```

Both of which ultimately run successfully. I'm can't confirm what the actual `strip` command output is, however.

---

I tested v8.1.2 and it works as expected.

This may be the result of the switch to recursive-readdir
https://github.com/prebuild/prebuild/blob/3b8401da1f0363156d4249d9dc7f12436a756aec/collect-artifacts.js#L3

**Comment by vweevers** [comment]
Yes, it's the first case ("it may only be stripping the first file").

> This may be the result of the switch to recursive-readdir

Correct, and apologies for the breaking change. Before 8.2.0, files in nested folders were not included. The default include regex is `\.node$`, which before only matched 1 file in your case, now 2.

There are 2 problems to solve here:

1. Should we not scan nested folders by default? Or tweak the default regex to only include top-level `.node` files? I'm not sure how to to best satisfy everyone's needs.
2. Fix stripping to correctly handle multiple files.

**Comment by zaro** [comment]
about 1. I think either solution is fine. I would personally go for the regex limiting to only top-level files.

**Comment by lovell** [comment]
Hello, I've opened PR #247 to temporarily revert these breaking changes.

**Comment by vweevers** [comment]
@zaro We've reverted the recursive feature in v8.2.1. You're more than welcome to open a new PR - taking the above into account. Thanks!

**Comment by vweevers** [comment]
Thought: what if we used a glob pattern rather than a regex? The default would be `*.node` and if you need nested files you could specify e.g. `**/*.node`.
