### ISSUE TITLE
Offline npm rebuild

### ISSUE THREAD

**Issue by GregoryNEUT** [prebuild/prebuild#257]
Hello,

My project needs to be installed **offline**. To be able to achieve that, I download all the `nodes_modules` in a server with internet access and then copy the `nodes_modules` and the `.node-gyp` into the offline server.

Usually a simple `npm rebuild` is enough to makes the `node_modules` to works on the new machine, but using `zeromq` package (instead of `zmq` old package) I get the following error : 

> npm rebuild
> 
> > zeromq@5.1.0 install /path/node_modules/zeromq
> > node scripts/prebuild-install.js || (node scripts/preinstall.js && node-gyp rebuild)
> 
> prebuild-install WARN install getaddrinfo ENOTFOUND github.com github.com:443
> 
> { Error: getaddrinfo ENOTFOUND github.com github.com:443
>     at errnoException (dns.js:50:10)
>     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:92:26)
>   code: 'ENOTFOUND',
>   errno: 'ENOTFOUND',
>   syscall: 'getaddrinfo',
>   hostname: 'github.com',
>   host: 'github.com',
>   port: 443 }

What can I do to make my `nodes_modules` to be able to get rebuilt offline?

Thanks

**Comment by vweevers** [comment]
`npm i --build-from-source`

**Comment by GregoryNEUT** [comment]
Totally work, praise to you mister @vweevers ! :)
