### ISSUE TITLE
prebuild -t 0.38.0 -r node-webkit fail on MacOS

### ISSUE THREAD

**Issue by akarsh42** [prebuild/prebuild#266]
Trying to do:(node-pty)
`prebuild -t 0.38.0 -r node-webkit`

the main error

> `prebuild info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
>   CXX(target) Release/obj.target/pty/src/unix/pty.o
> ../src/unix/pty.cc:643:10: error: use of undeclared identifier 'openpty'
>   return openpty(amaster, aslave, name, (termios *)termp, (winsize *)winp);
>       
> ../src/unix/pty.cc:692:10: error: use of undeclared identifier 'forkpty'
>   return forkpty(amaster, name, (termios *)termp, (winsize *)winp);
>          
> 2 errors generated.`

find the error below: 
`prebuild info begin Prebuild version 10.0.0
prebuild info build Preparing to prebuild node-pty@0.9.0 for node-webkit 0.38.0 on darwin-x64 using nw-gyp
prebuild info spawn /usr/local/bin/python2
prebuild info spawn args [ '/Users/kh1095/.nvm/versions/node/v11.14.0/lib/node_modules/prebuild/node_modules/nw-gyp/gyp/gyp_main.py',
prebuild info spawn args   'binding.gyp',
prebuild info spawn args   '-f',
prebuild info spawn args   'make',
prebuild info spawn args   '-I',
prebuild info spawn args   '/Volumes/data/nw-local-server-example-master/node_modules/node-pty/build/config.gypi',
prebuild info spawn args   '-I',
prebuild info spawn args   '/Users/kh1095/.nvm/versions/node/v11.14.0/lib/node_modules/prebuild/node_modules/nw-gyp/addon.gypi',
prebuild info spawn args   '-I',
prebuild info spawn args   '/var/folders/8y/tjq58zts1xddnw8c6fhyvtlx3v_6wn/T/prebuild/node-webkit/0.38.0/common.gypi',
prebuild info spawn args   '-Dlibrary=shared_library',
prebuild info spawn args   '-Dvisibility=default',
prebuild info spawn args   '-Dnode_root_dir=/var/folders/8y/tjq58zts1xddnw8c6fhyvtlx3v_6wn/T/prebuild/node-webkit/0.38.0',
prebuild info spawn args   '-Dnode_gyp_dir=/Users/kh1095/.nvm/versions/node/v11.14.0/lib/node_modules/prebuild/node_modules/nw-gyp',
prebuild info spawn args   '-Dnode_lib_file="/var/folders/8y/tjq58zts1xddnw8c6fhyvtlx3v_6wn/T/prebuild/node-webkit/0.38.0/<(target_arch)/node.lib"',
prebuild info spawn args   '-Dnw_lib_file="/var/folders/8y/tjq58zts1xddnw8c6fhyvtlx3v_6wn/T/prebuild/node-webkit/0.38.0/<(target_arch)/nw.lib"',
prebuild info spawn args   '-Dmodule_root_dir=/Volumes/data/nw-local-server-example-master/node_modules/node-pty',
prebuild info spawn args   '-Dnode_engine=v8',
prebuild info spawn args   '--depth=.',
prebuild info spawn args   '--no-parallel',
prebuild info spawn args   '-Dv13=1',
prebuild info spawn args   '--generator-output',
prebuild info spawn args   'build',
prebuild info spawn args   '-Goutput_dir=.' ]
prebuild info spawn make
prebuild info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
  CXX(target) Release/obj.target/pty/src/unix/pty.o
../src/unix/pty.cc:643:10: error: use of undeclared identifier 'openpty'
  return openpty(amaster, aslave, name, (termios *)termp, (winsize *)winp);
         ^
../src/unix/pty.cc:692:10: error: use of undeclared identifier 'forkpty'
  return forkpty(amaster, name, (termios *)termp, (winsize *)winp);
         ^
2 errors generated.
make: *** [Release/obj.target/pty/src/unix/pty.o] Error 1
prebuild ERR! build error 
prebuild ERR! stack Error: `make` failed with exit code: 2
prebuild ERR! stack     at ChildProcess.onExit (/Users/kh1095/.nvm/versions/node/v11.14.0/lib/node_modules/prebuild/node_modules/nw-gyp/lib/build.js:271:23)
prebuild ERR! stack     at ChildProcess.emit (events.js:193:13)
prebuild ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:255:12)
prebuild ERR! not ok 
prebuild ERR! build Error: `make` failed with exit code: 2
prebuild ERR! build     at ChildProcess.onExit (/Users/kh1095/.nvm/versions/node/v11.14.0/lib/node_modules/prebuild/node_modules/nw-gyp/lib/build.js:271:23)
prebuild ERR! build     at ChildProcess.emit (events.js:193:13)
prebuild ERR! build     at Process.ChildProcess._handle.onexit (internal/child_process.js:255:12)`

**Comment by vweevers** [comment]
That's a problem you'll have to solve yourself, because it isn't caused by prebuild. Good luck!
