### ISSUE TITLE
Build error with the latest node version 14.15.1

### ISSUE THREAD

**Issue by Lynn-cc** [prebuild/prebuild#272]
platform: window x64
prebuild: latest, 10.0.1

The error occurs when i run `npm install serialport --save-dev`

And when i reinstall node@10.x, the problem solved.

**Comment by vweevers** [comment]
Likely not an issue with `prebuild`. I recommend opening a ticket in [serialport](https://github.com/serialport/node-serialport) and to give them more info (most importantly: the output of `npm install serialport`). Good luck!
