### ISSUE TITLE
Prebuild for Electron 12.0.0-beta.1 builds a file named "electron-v85" that is actually built for ABI 87

### ISSUE THREAD

**Issue by kevinmehall** [prebuild/prebuild#273]
In https://github.com/tessel/node-usb, running, `npm run prebuild -- -r electron -t 11.0.0 -t 12.0.0-beta.1 ` produces only one file `prebuilds/usb-v1.6.4-electron-v85-linux-x64.tar.gz`, containing a `.node` built for ABI 87. I would expect to see two packages for 85 and 87 each containing a build for the corresponding version.

Building for Electron 11 alone with `npm run prebuild -- -r electron -t 11.0.0` produces a file of the same name, but it is indeed correctly built against 85.

Building for Electron 12.0.0-beta1 alone produces the erroneous file, which seems to overwrite the Electron 11 build.

Via https://github.com/tessel/node-usb/issues/409

**Comment by karniv00l** [comment]
This is a problem with the `node-abi` package. It returns ABI from Electron `v11` because its registry doesn't contain `v12` (https://github.com/lgeiger/node-abi/blob/42932775e72f8886f87b518fadb25d08b5f8c3da/abi_registry.json). I'm opening issue there.
