### ISSUE TITLE
Builds produced for electron 11 are broken

### ISSUE THREAD

**Issue by Julusian** [prebuild/prebuild#275]
This is a snippet of a discovery found in https://github.com/serialport/node-serialport/issues/2191#issuecomment-819149005

I have raised an issue (https://github.com/lgeiger/node-abi/issues/103) with node-abi to investigate a fix, but I don't know if they will be willing to do anything 

When building for electron 11, prebuild is using the headers for v11.0.0-beta.11. However due to some changes introduced in v11.0.0-beta.12, these binaries can be incompatible with other versions of electron 11.
I have confirmed this in that library by trying to run builds produced directly from node-gyp using both v11.0.0-beta.11 and v11.0.0-beta.12 headers in various versions of electron 11. I also manually applied [this patch](https://github.com/electron/electron/compare/v11.0.0-beta.11...v11.0.0-beta.12#diff-5115fa205eb6e02fcf3815ec5098c8bb6e1de0f29b5c23425349f9db1b6ca6ec) onto my cached v11.0.0-beta.11 headers to confirm it is the snippet at fault.

The fix is simply to use a different version of the headers than node-abi says. Hopefully this is a one-off and wont be a recurring issue in future electron versions

**Comment by lovell** [comment]
@Julusian Is this still an issue, or can this now be closed?

**Comment by Julusian** [comment]
I have no idea. I now avoid any non node-api native library, to avoid issues such as this.

**Comment by lovell** [comment]
@Julusian Thank you, it looks like serialport migrated to Node-API in late 2021 / early 2022 as part of https://github.com/serialport/node-serialport/pull/2305 so I'll close.
