### ISSUE TITLE
What is the meaning of "a" in `--include-regex "\.(node|a)$"`

### ISSUE THREAD

**Issue by Leslie-Wong-H** [prebuild/prebuild#303]
Context:
Try to add Windows support back to this fork of [opencv4nodejs](https://github.com/soruly/opencv4nodejs/compare/master...Leslie-Wong-H:opencv4nodejs:master)
Since the original windows-2016 is no longer available at GitHub actions, use windows-2019 to target nodejs 16 and 18. 
Yet keep stuck in the publish step. https://github.com/Leslie-Wong-H/opencv4nodejs/actions/runs/4752357606/jobs/8442612069
```shell
Installing prebuilt OpenCV v4.1.1-7 for platform win32
Done.
'a' is not recognized as an internal or external command,
operable program or batch file.
Error: Process completed with exit code 255.
```
![image](https://user-images.githubusercontent.com/27696701/233319899-88869c20-8186-4403-9ced-84727cc6b98d.png)

No idea where "a" is coming from, probably "--include-regex".

Fire an issue here to get some hints, hopefully.

**Comment by Leslie-Wong-H** [comment]
PR Link: https://github.com/Leslie-Wong-H/opencv4nodejs/pull/1

**Comment by lovell** [comment]
It looks like the regex will need to be correctly quoted/escaped for use with the Windows command line, otherwise Windows will treat `a` as a command to run.

It might be easier to create a `.prebuildrc` file when working cross-platform, e.g. https://github.com/lovell/sharp/blob/main/.prebuildrc

**Comment by lovell** [comment]
I hope this information helped. Please feel free to re-open with more details if further assistance is required.
